# Generated by Django 2.2 on 2019-04-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190407_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='place',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
