# Generated by Django 2.2 on 2019-04-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190407_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='place',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
