# Generated by Django 2.2 on 2019-04-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190408_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='color',
            field=models.CharField(default='grey', max_length=100),
        ),
    ]
