# Generated by Django 2.2 on 2019-04-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_timeslot_color'),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE EXTENSION IF NOT EXISTS postgis',
        )
    ]
