# Generated by Django 2.2 on 2019-04-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('events', '0009_auto_20190428_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.City'),
        ),
    ]
