# Generated by Django 2.2 on 2019-05-11 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_plan_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='parent_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Plan'),
        ),
    ]
