# Generated by Django 2.2 on 2019-05-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_plan_parent_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
