# Generated by Django 2.2.3 on 2019-07-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.CharField(default='/static/assets/images/default.png', max_length=255),
        ),
    ]
