# Generated by Django 2.2.3 on 2019-07-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_profile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='avatar',
        ),
    ]
