# Generated by Django 2.2.3 on 2019-07-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20190715_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='candle_settings',
            field=models.TextField(default='{}'),
        ),
    ]
