# Generated by Django 2.2.3 on 2019-07-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_profile_candle_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='marketwatch_settings',
            field=models.TextField(default='{}'),
        ),
    ]
