from django.conf.urls import url

from . import views


PROFILE_SETTINGS_FIELDS = [
    'name',
    'looking_for',
    'birthday',
    'lower_age_bound',
    'upper_age_bound',
    'purpose',
    'build',
    'alcohol_attitude',
    'smoking_attitude',
]

PROFILE_SETTINGS_URLS = [
    url(r'^profile/{}/$'.format(setting),
        views.ProfileSetting(setting).as_view(),
        name='set_{}'.format(setting))
    for setting in PROFILE_SETTINGS_FIELDS
]

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^accounts/signup/$', views.signup, name='account_signup'),
    url(r'^accounts/signup/(?P<repost_source>\w+)/$',
        views.signup_from_repost),
    url(r'^accounts/social/signup/$', views.social_signup),
    url(r'^profile/(?P<profile_id>\d+)/$',
        views.profile,
        name='profile'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^upload/$', views.file_upload, name='upload'),
    url(r'^question/(?P<id>\d+)/$',
        views.answer_question,
        name='answer_question'),
    url(r'^answer/(?P<question_id>\d+)/delete/$',
        views.delete_answer,
        name='delete_answer'),
    url(r'^profile/avatar/$', views.add_avatar, name='add_avatar'),
    url(r'^profile/avatar/(?P<photo_id>\d+)/$',
        views.avatar_setting,
        name='set_avatar'),
    url(r'^emailcheck/$', views.email_check, name='email_check'),
    url(r'^profile/updatesearch/$',
        views.update_search,
        name='update_search'),
    url(r'^profile/updatecharacter/$', views.update_character,
        name='update_character'),
    url(r'^changeemail/$', views.change_email, name='change_email'),
    url(r'^photo/(?P<photo_id>\d+)/delete/$', views.delete_photo,
        name='delete_photo'),
    url(r'^photo/(?P<photo_id>\d+)/restore/$', views.restore_photo,
        name='restore_photo'),
    url(r'^changepass/$', views.change_password, name='changepass'),
    url(r'^visits/count/$',
        views.unread_visits_count,
        name='unread_visits_count'),
    url(r'^visits/(?P<visit_id>\d+)/delete/$', views.delete_visit,
        name='delete_visit'),
    url(r'^visits/unread/$',
        views.unread_visits,
        name='unread_visits'),
    url(r'^emulationsubscribe/$',
        views.subscribe_for_emulation,
        name='emulation_subscribe'),
    url(r'^unsubscribe',
        views.unsubscribe,
        name='email_unsubscribe'),
    url(r'^test/$', views.test, name='test_page'),
    url(r'^terms/$', views.terms, name='terms'),
    url(r'^terms/en/$', views.terms_en, name='terms_en'),
    url(r'^conf_policy/$', views.conf_policy, name='conf_policy'),
    url(r'^conf_policy/en/$',
        views.conf_policy_en,
        name='conf_policy_en'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contacts/$', views.contacts, name='contacts'),
    url(r'^invisible/on/$',
        views.invisible_on,
        name='invisible_on'),
    url(r'^invisible/off/$',
        views.invisible_off,
        name='invisible_off'),
    url(r'^profile/name/$', views.change_name, name='set_name'),
    url(r'^profile/settings/$', views.settings_page, name='settings_page'),
    url(r'^toggleemail/$', views.toggle_email_subscription, name='toggle_email_subscription'),
    *PROFILE_SETTINGS_URLS
]
