# Generated by Django 2.2.3 on 2019-07-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmation',
            name='kind',
            field=models.CharField(choices=[('REGISTRATION', 'REGISTRATION'), ('RECOVERY', 'RECOVERY')], default='REGISTRATION', max_length=20),
        ),
    ]
