# Generated by Django 2.2.3 on 2019-07-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_emailconfirmation_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='kind',
            field=models.CharField(choices=[('REGISTRATION', 'REGISTRATION'), ('RECOVERY', 'RECOVERY')], default='REGISTRATION', max_length=20, unique=True),
        ),
    ]
