# Generated by Django 2.2.3 on 2019-07-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0003_auto_20190713_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='kind',
            field=models.CharField(choices=[('REGISTRATION', 'REGISTRATION'), ('RECOVERY', 'RECOVERY')], default='REGISTRATION', max_length=20),
        ),
    ]
